-- AlterTable
ALTER TABLE "buttons" ALTER COLUMN "server_id" SET DATA TYPE TEXT,
ALTER COLUMN "channel_id" SET DATA TYPE TEXT,
ALTER COLUMN "role_id" SET DATA TYPE TEXT,
ALTER COLUMN "redirect_id" SET DATA TYPE TEXT,
ALTER COLUMN "message_id" SET DATA TYPE TEXT;
